name: Build And Deploy exercise
on:
  push:
    branches:
      - feature/duplo-dockerization
      - sandbox
env:
  DUPLO_HOST: https://test13.duplocloud.net/
  DUPLO_TOKEN: ${{secrets.DUPLO_TOKEN}}
  SERVICE_NAME: backend                        
  DUPLO_TENANT: exercise 
jobs:
  build:
    runs-on: alpine-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Duplo Setup
      uses: duplocloud/actions/setup@v0.0.5

    - name: Build and Push Docker Image
      uses: duplocloud/actions/build-image@v0.0.5
      id: build-and-push
      with:
        repo: ${{ env.SERVICE_NAME }}
        extra-tags:  ${{ github.sha }}
        platforms: linux/amd64
        push: true
    outputs:
      image: "${{ steps.build-and-push.outputs.image }}:${{ github.sha }}"
  deploy:
    runs-on: alpine-latest
    needs:
    - build
    steps:
    - name: Duplo Setup
      uses: duplocloud/actions/setup@v0.0.5

    - name: Update Main Service 
      uses: duplocloud/actions/update-service@v0.0.5
      with:
        service: ${{ env.SERVICE_NAME }}
        image: ${{ needs.build.outputs.image }}
